//! API
export const API = "http://ec2-54-180-29-60.ap-northeast-2.compute.amazonaws.com:8080";

// 로그인
export const APIS = {
  POST_USER_SIGNUP_JWT: `${API}/api/users/normal`,
  POST_PHARM_SIGNUP_JWT: `${API}/api/users/store`,
  POST_USER_SIGNUP_AUTH: "",
  POST_PHARM_SIGNUP_AUTH: "",
  POST_LOGIN_JWT: `${API}/login`,
  POST_LOGIN_AUTH: `${API}/api/auth`,
  POST_REISSUE_REFRESH_TOKEN: "",
  POST_LOGOUT: `${API}/api/auth/logout`,
  PATCH_FINDPW: "",
  DELETE_SIGNOUT: `${API}/api/users`,
  GET_PHARMLIST: `${API}/api/store`,
  GET_PHARMDETAILS: `${API}/api/store`,
  GET_REVIEWS: `${API}/api/store`,
  POST_REVIEWS: `${API}/api/store`,
  PATCH_REVIEWS: "",
  DELETE_REVIEWS: "",
  POST_REPORT_REVIEW: "",
  POST_COMMENT: "",
  PATCH_COMMENT: "",
  DELETE_COMMENT: "",
  GET_USER_INFO: "",
  PATCH_USER_IMG: "",
  PATCH_USER_INFO: "",
  GET_MYLIKEDPHARMS: "",
  GET_MYREVIEWS: "",
  POST_LIKE: "",
  GET_ADMIN_CERTS: "",
  POST_ADMIN_CERTIFY: "",
  POST_ADMIN_DENY: "",
  GET_ADMIN_REPORTED: "",
  DELETE_ADMIN_REVIEW_DELETE: "",
  POST_ADMIN_REVIEW_RESTORE: "",
  GET_ADMIN_USERS: "",
  POST_ADMIN_FIRE: "",
  POST_ADMIN_BLOCK: "",
};
